# Generated by Django 3.2 on 2021-10-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='name',
            new_name='rname',
        ),
    ]
