# Generated by Django 3.2 on 2021-10-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_rname_reg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='loc',
            new_name='sloc',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='pas',
            new_name='spas',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='phone',
            new_name='sphone',
        ),
    ]
