# Generated by Django 3.0.5 on 2022-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211011_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='pho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
            ],
        ),
    ]
