# Generated by Django 3.0.5 on 2022-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pho'),
    ]

    operations = [
        migrations.CreateModel(
            name='pho1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
                ('Time1', models.CharField(max_length=60)),
            ],
        ),
    ]
