# Generated by Django 3.0.5 on 2022-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_pho2'),
    ]

    operations = [
        migrations.CreateModel(
            name='pho3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
                ('Time1', models.CharField(max_length=60)),
                ('des', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
