# Generated by Django 4.1 on 2022-08-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_pho3"),
    ]

    operations = [
        migrations.CreateModel(
            name="pho4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.CharField(max_length=60)),
                ("date1", models.CharField(max_length=60)),
                ("Time1", models.CharField(max_length=60)),
                ("des", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=50)),
                ("Location", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="pho",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pho1",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pho2",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pho3",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
